kind: workflow
name: my workflow 2
apiVersion: automation.cloudbees.io/v1alpha1

on:
  workflow_dispatch: null

jobs:
  hello:
    steps:
      - uses: docker://alpine:3.20
        run: echo "hello world"